[package]
name = "the_flappy_thing"
version = "0.1.0"
authors = ["Abderrahmane Boulgheraif <b-abderrahmane@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
